### PR TITLE
dyacob gff_geez updates 2017/9/2

### PR DESCRIPTION
**Pull request by dyacob**
I believe this creates a pull request of the gff_geez branch of the dyacob fork into the MakaraSok fork, of the keymanapp/keyboards repository.

### CODE REVIEW

**Comment by LornaSIL** [comment]
I tested the Ge'ez Typing Table. The pdf discusses two keyboards, but there is only one keyboard in the PR. I wonder if the other keyboard is submitted separately maybe the pdf should have the "Typing all languages" section removed?

I have not used this keyboard before, but it seems to me that there are some confusing sequences. For instance I can type (I'm not typing the comma, I'm just referencing the different keystroke rule in the table):
* "h,ho" and "hho" and get the same character. In the first instance I really wanted two different characters (ህ and ሆ vs ኆ)
* "s,so" and "sso" and get the same character. In the first instance I really wanted two different characters (ስ and ሶ vs ሦ).
* "S,So" and "SSo" and get the same character. In the first instance I really wanted two different characters (ጽ and ጾ vs ፆ).

A similar situation exists with the vowels:
* "i,e" and "ie" produce the same fidel even tho I wanted two fidels in the first instance (ኢ and እ vs ኤ).
* "e,a" and "ea" produce the same fidel even tho I wanted two fidels in the first instance (እ and አ vs ኣ).
* "e,e,o,o" becomes two fidels (but the wrong ones: ዖኦ vs ዕዖ).

Now maybe none of these will happen in real life and it doesn't matter. I was merely testing the chart and came across these. 

Also, the rules for the Zaima notation in the document are not consistent with the keystroke results (_2, _4, _6, _8, and _0 do not work as documented).

Lastly, the ico file is 256x256. I was happy to see that size of icon was ok when I turned on the keyboard in Windows. However, I did find that that size does not display properly in .kmp file. You can see it only displays the top left part of the fidel:
image

It might be best to go back to 16x16? Or maybe it's a bug in Keyman?

In the welcome.htm file there is a link to Abyssinica SIL. We've moved the home page of the font. It will autoredirect, but if you could fix it, that would be ideal: https://software.sil.org/abyssinica/ or https://software.sil.org/abyssinica/download/

**Comment by DavidLRowe** [comment]
Marc Durdin wrote about another keyboard: " Keyman will use a higher resolution icon on HiDPI screens in the Windows language menu (not yet in the Keyman UI, perhaps later this year); typically a 16x16 and a 48x48 icon should be enough to make use of anything up to 300% scaling (which is rare)." So if you can make an .ico file with those two sizes, then that would work, otherwise just use the 16x16 one.

**Comment by dyacob** [comment]
The sequence doubling based composition (like "ss" to get to the ሥ family) is very much by design and present in all of the gff_ keyboards where the phonetically redundant letters are found for a language.

The Zaima composition has changed.  The PDF manual and welcome.htm pages have not yet been updated.

The issue with the too-large icon applied in the Desktop Configuration screen (its fine in the menu bar) is reported in Keyman App issue 297:  https://github.com/keymanapp/keyman/issues/297

**Comment by dyacob** [comment]
...earlier I thought this discussion was under the PR at the main repository and not MakaraSok fork.  Its clear to me now.  If getting the keyboards into the main repository isn't terribly urgent, I can devote time to updating the manuals.  Which may add another week for me to get through.

**Comment by dyacob** [comment]
The PDF manual is now updated and its Word doc added to the source folder.

**Review by DavidLRowe — APPROVED** [review]

**Comment by DavidLRowe** [comment]
This pull request (#1) was issued against Makara's `master` branch, rather than the `gff_geez` branch. I didn't notice that until after I had merged, so I reverted that commit (done in PR #8). 

@dyacob Please resubmit these changes in a new pull request on the `gff_geez` branch. Thanks!

**Pull request merged**
